version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epic_db
    networks:
      epic-mysql-net:

  epic-challenge:
    container_name: epic-challenge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      epic-mysql-net:
    restart: on-failure
networks:
  epic-mysql-net: